### ISSUE TITLE
Event Branch PR - Description of functional components

### ISSUE THREAD

**Issue by mertkantaroglu** [mertkantaroglu/Math-Magician#4]
Hello,

In this project, I used the useState hook as below.

```
function Calculator() {
  const [state, setState] = useState({ total: 0, next: null, operation: null });

  const { total, next, operation } = state;

  const onClickHandler = (event) => {
    const action = event.target.textContent;
    const newState = calculate(state, action);
    setState(newState);
  }; ...
```

In this function, the useState hook is used to define the objects of total, next, and operation as well as the initial values of the state. 

With this hook, I was able to use the objects in my calculation function.

Kindly review my project and let me know your thoughts.

Best,
Mert

**Comment by julie-ify** [comment]
Hi @mertkantaroglu,

## Highlights!
- Good feature branch name ✔️
- Good code organization and working app ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
